// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/Content.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Header.tsx";
import * as $$3 from "./islands/Layout.tsx";
import * as $$4 from "./islands/Sider.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/Content.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Header.tsx": $$2,
    "./islands/Layout.tsx": $$3,
    "./islands/Sider.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
